### ISSUE TITLE
大佬，prepare_latent_buckets.py文件不存在

### ISSUE THREAD

**Issue by yangy996** [IDEA-CCNL/Taiyi-Diffusion-XL#2]

**Comment by wxj630** [comment]
<img width="186" alt="image" src="https://github.com/IDEA-CCNL/Taiyi-Diffusion-XL/assets/19636285/d03aa3a7-1d25-4aca-ae08-a559e3384f94">
有啊你拉下最新的代码

**Comment by yangy996** [comment]
![(5E%5JX55MX8NIC)8QBG@7B](https://github.com/IDEA-CCNL/Taiyi-Diffusion-XL/assets/15188456/202ba390-a764-4f29-ac7b-217afee1d030)
没有这个py文件

**Comment by yangy996** [comment]
prepare_buckets_latents.py

**Comment by yangy996** [comment]
> <img alt="image" width="186" src="https://private-user-images.githubusercontent.com/19636285/320749174-d03aa3a7-1d25-4aca-ae08-a559e3384f94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDgwNTMsIm5iZiI6MTcxMjY0Nzc1MywicGF0aCI6Ii8xOTYzNjI4NS8zMjA3NDkxNzQtZDAzYWEzYTctMWQyNS00YWNhLWFlMDgtYTU1OWUzMzg0Zjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA3MjkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YmIzMGVhZWMyNjZlNWFmYWM2MWQ5NmZkNmNhNzQwOGZmNjVlMDI0ZTVlMDdmMmY4OWZlZjNmNDhlYTI1YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t-74tltR15BFMSpj9IAk4aAep-P9bQgwJMZUBDjbyBA"> 有啊你拉下最新的代码

大佬，这个文件prepare_buckets_latents.py是不是没有提交呀

**Comment by wxj630** [comment]
好的，不小心.gitignore了，现在提交了
