### ISSUE TITLE
运行报错，在哪里修改占用显卡的个数呢？

### ISSUE THREAD

**Issue by yangy996** [IDEA-CCNL/Taiyi-Diffusion-XL#3]
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by wxj630** [comment]
config/accelerate_config/default_config.yaml

**Comment by yangy996** [comment]
> config/accelerate_config/default_config.yaml

多谢多谢
