### ISSUE TITLE
新训练模型图片如何实现自动标注输出meta_clean.json文件，readme缺少了这部分说明

### ISSUE THREAD

**Issue by mario0718** [IDEA-CCNL/Taiyi-Diffusion-XL#4]
新训练模型图片如何实现自动标注输出meta_clean.json文件，readme缺少了这部分说明

**Comment by mario0718** [comment]
![1](https://github.com/IDEA-CCNL/Taiyi-Diffusion-XL/assets/46362714/0d27f34b-2758-41ee-86b7-d8f323f6fb52)

**Comment by wxj630** [comment]
看起来是json加载的问题，你试下单独json.load(f)这个文件有没有问题
